name: healthcare_flutter_app
description: A comprehensive healthcare Flutter application with multiple screens
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/doctors/
    - assets/images/
